INSERT IGNORE INTO field_enum (id, field, value, name, meta) VALUES
('enum-access_protocol-http', 'access_protocol', 'http', 'HTTP', '{}'),
('enum-access_protocol-tcp', 'access_protocol', 'tcp', 'TCP', '{}'),
('enum-access_protocol-tls', 'access_protocol', 'tls', 'TLS', '{}'),
('enum-access_protocol-ssh', 'access_protocol', 'ssh', 'SSH', '{}'),
('enum-access_protocol-rdp', 'access_protocol', 'rdp', 'RDP', '{}'),
('enum-access_protocol-socks5', 'access_protocol', 'socks5', 'SOCKS5', '{}'),
('enum-access_protocol-ss5', 'access_protocol', 'ss5', 'SS5', '{}'),
('enum-access_protocol-udp', 'access_protocol', 'udp', 'UDP', '{}'),
('enum-access_service_type-http', 'access_service_type', 'http', 'HTTP', '{}'),
('enum-access_service_type-https', 'access_service_type', 'https', 'HTTPS', '{}'),
('enum-access_service_type-raw_tcp', 'access_service_type', 'raw_tcp', 'Raw TCP', '{}'),
('enum-access_service_type-raw_udp', 'access_service_type', 'raw_udp', 'Raw UDP', '{}'),
('enum-access_service_type-ssh', 'access_service_type', 'ssh', 'SSH', '{}'),
('enum-access_service_type-rdp', 'access_service_type', 'rdp', 'RDP', '{}'),
('enum-access_service_type-socks5', 'access_service_type', 'socks5', 'SOCKS5', '{}'),
('enum-access_service_type-ss5', 'access_service_type', 'ss5', 'SS5', '{}'),
('enum-access_service_type-tls_passthrough', 'access_service_type', 'tls_passthrough', 'TLS Passthrough', '{}'),
('enum-tls_mode-none', 'tls_mode', 'none', 'None', '{}'),
('enum-tls_mode-passthrough', 'tls_mode', 'passthrough', 'Passthrough', '{}'),
('enum-tls_mode-terminate', 'tls_mode', 'terminate', 'Terminate', '{}'),
('enum-access_auth_mode-proxy_token', 'access_auth_mode', 'proxy_token', 'Proxy Token', '{}');
